### ISSUE TITLE
Can't record Unigram

### ISSUE THREAD

**Issue by MarcAnt01** [robmikh/SimpleRecorder#18]
For some reasons if I use Unigram the app won't record anything, both using screen capture and app one

**Comment by robmikh** [comment]
Could you clarify what you mean by "won't record anything"? Is the recording black? Does the video not encode properly? It would also be helpful if you could share what build of Windows you're seeing this behavior on.

I'm not familiar with the Unigram app, but applications have the ability to mark themselves as non-capturable. In that event, we will draw black where the window should be.

**Comment by MarcAnt01** [comment]
Hi, thanks for the reply. The video was getting stuck while using Unigram. The ability to se the app as non-capturable is limited to secret chats and auto-destruction media, that I wasn't using. I tried to record it, but this morning it's working properly, even if yesterday it was never working (did several tries before opening this ticket)

**Comment by MarcAnt01** [comment]
Hello @robmikh after further research, this is due by the app that once you minimize the window can't record the other app window. I fixed that by adding extended execution in my fork

**Comment by robmikh** [comment]
Ah yes, without extended background execution the thread that runs the encoding gets suspended. That's a limitation of the sample. To limit confusion I have stopped the recording when suspended.
