### ISSUE TITLE
Encoding doesn't stop after failure

### ISSUE THREAD

**Issue by MarcAnt01** [robmikh/SimpleRecorder#22]
Repro steps:
1. Set a resolution higher than the one in your screen keeping the checkbox disabled;
2. Select windows recording.

The window still has yellow borders
![image](https://user-images.githubusercontent.com/43090263/90808627-9cf54600-e320-11ea-9245-e12423c17560.png)

**Comment by robmikh** [comment]
Thanks for finding this!
