### ISSUE TITLE
Command bar overlaps the video player ui when full screen

### ISSUE THREAD

**Issue by MarcAnt01** [robmikh/SimpleRecorder#28]
![image](https://user-images.githubusercontent.com/43090263/91315293-cea25d00-e7b7-11ea-88a0-4cf796db29fd.png)

**Comment by robmikh** [comment]
I think this happens because of the way I cheated to put the same command bar across all pages. Unfortunately I can't find a way to know when we enter fullscreen mode to hide the command bar... I may just have to disable the fullscreen button.

**Comment by robmikh** [comment]
"Fixed" with 5c1ab67c526e6dbf0720c120a39302dad0fd5122
