### ISSUE TITLE
1280x720 resolution issues

### ISSUE THREAD

**Issue by Paputto0** [robmikh/SimpleRecorder#29]
Heya,

After the latest (28.08) update the 1280x720 resolution started to produce distorted output.
1. The app captures a lot less area than it should (both in window and screen mode). It looks like for FHD screen it captures a fraction of it (720/1080).
2. The colors are well distorted. Some encoding issues?
3. The sharpness is way off

Changing the bitrate doesn't help. Other resolutions are perfectly OK, but I'm not using them on day-to-day basis (I need smallest file size and 720p is a good choice for me).

Output video for 720p/9mbps/30fps in the zip attached.

Cheers & keep up the good work!

[capture.zip](https://github.com/robmikh/SimpleRecorder/files/5141667/capture.zip)

**Comment by robmikh** [comment]
Hmmm I think this regressed when I changed the capture buffer size to match the final encoded output size. This worked fine when the window was smaller than the target resolution but the wheels come off when the window is larger than the target resolution.

Thanks for reporting this! I'll either have to revert to the old behavior or do some scaling.
