### ISSUE TITLE
Encoder exception

### ISSUE THREAD

**Issue by MarcAnt01** [robmikh/SimpleRecorder#31]
Some users have this issues with the encoder, it is present also in my fork, if you want I can send you error details from AppCenter via mail.
Users that have this kind of issue can never record the screen (apps are fine)
![image](https://user-images.githubusercontent.com/43090263/99145651-dd8b0400-2670-11eb-8371-17eff464d238.png)

**Comment by robmikh** [comment]
Unfortunately there isn't enough information to figure out what is going on.

What's the resolution? Do you get the error if you try to record a window that is the same size as the monitor? Does it work if you turn down some of the settings (bitrate/fps)?

**Comment by MarcAnt01** [comment]
@robmikh I don't have this issue, but some users of mine do, here's what one of them said
![image](https://user-images.githubusercontent.com/43090263/99656940-c88de680-2a5d-11eb-85a9-69f08749502f.png)

**Comment by robmikh** [comment]
Hmm that makes me think the driver or available registered encoders doesn't support the encoding mode used under the covers by the Transcoding API. Unfortunately this quickly gets into media territory that I'm not super familiar with yet.

What GPU are they running?

**Comment by FrayxRulez** [comment]
Adding a bit of context. 
The exception is raised by `PrepareTranscodeResult.TranscodeAsync` so I’m pretty sure that `CanTranscode` is set to false, so your guess @robmikh is likely correct.

**Comment by MarcAnt01** [comment]
The GPU of the user is an Intel UHD Graphics 620, but I have the same GPU and the app works properly for me on 2004, I'll try to setup a vm in order to attempt to reproduce the issue

**Comment by robmikh** [comment]
If you set up a VM, it will likely be using WARP and a software encoder. It likely won't reproduce the issue (for the same reasons, at least).

Could we get a dxdiag from the machine?

**Comment by MarcAnt01** [comment]
[DxDiag.txt](https://github.com/robmikh/SimpleRecorder/files/5573340/DxDiag.txt)

**Comment by MarcAnt01** [comment]
Hey @robmikh , sorry for pinging you, have you found out anything about this issue?

**Comment by robmikh** [comment]
Sorry, but there isn't enough here to debug this issue.
