### ISSUE TITLE
audio recording?

### ISSUE THREAD

**Issue by balintmaci** [robmikh/SimpleRecorder#33]
Is it possible to record the audio output as well? Could it be added as a feature?

**Comment by robmikh** [comment]
See issue #21 for more of an explanation and some possibilities if you're interested in the APIs involved.

It could be something to be explored in the future, but at the moment it's not on my to-do list. This sample was built mainly to demonstrate video encoding, as I work on the Windows.Graphics.Capture API. I am much less familiar with audio.
