### ISSUE TITLE
audio???

### ISSUE THREAD

**Issue by mardulas** [robmikh/SimpleRecorder#34]
Why the f*** doesn't it record audio 🤷‍♂️

**Comment by MarcAnt01** [comment]
Because the API used by this app don't support it, also no reason to be so rude

**Comment by robmikh** [comment]
See issue #21.

In short, this is a sample on how to use the Windows.Graphics.Capture and Windows.Media.Transcoding APIs to encode video. Audio is outside the scope of this project.

If you'd like to add audio, I'd look into the WASAPI loop back documentation. You'll then have to provide the samples and time stamps to the `MediaStreamSource` object.
