### ISSUE TITLE
Object Reference not set , on latest version 

### ISSUE THREAD

**Issue by harmandeep-singh** [robmikh/SimpleRecorder#36]
Recording Failed 
Uh-oh! Something went wrong! 
0x8004003 - Object reference not set to an instance of an object

**Comment by robmikh** [comment]
That error generally gets thrown by the video driver if the settings you've selected don't match its capabilities. What settings did you use? Could you try lowering the frame rate or resolution? Were you trying to record a window or a monitor?

**Comment by harmandeep-singh** [comment]
👍 @robmikh  : Thank You  issue is fixed , after switch from nvidia graphic to intel graphics in display setting options
