### ISSUE TITLE
Why aren't you giving app executable or .msixbundle in releases section of GitHub for new releases?

### ISSUE THREAD

**Issue by clicky6** [robmikh/SimpleRecorder#38]
Why aren't you giving app executable or .msixbundle in releases section of GitHub for new releases?

**Comment by robmikh** [comment]
I originally did it to make installation easier on test machines during my day job. But now that it's in the store, that motivation is gone.

The problem with the releases I've previously put up is that they are signed with a test cert that doesn't last very long. I don't really want to shell out the money or get a physical business address to get a grown up cert, so I've stopped all together.

Sorry for the inconvenience! Your best bet is to get new versions from the store or compile it yourself.
