### ISSUE TITLE
Build artifacts in Github release

### ISSUE THREAD

**Issue by nickdex** [robmikh/SimpleRecorder#39]
Microsoft store forces you to login before you can install anything. 
Can you please upload the installer to Github Releases

**Comment by robmikh** [comment]
I'm able to download free applications without an account from the store without issue. The store prompts me to sign in, but there is a button to decline and the download will still happen. Are you seeing a different behavior?

There have been [previous requests](https://github.com/robmikh/SimpleRecorder/issues/38) for updated installers, but the issue of properly signing these without paying for a certificate prevents me from doing so. When the test certificate expires, the installer will no longer be valid, [as others have run into](https://github.com/robmikh/SimpleRecorder/issues/15).

I don't see a way around this at the moment. I'm going to close this issue, but feel free to let me know here if I've missed something.

**Comment by robmikh** [comment]
I should note that I have another project that is unpackaged [here](https://github.com/robmikh/CaptureVideoSample). The recording capabilities are similar.
