### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by mauriceackel** [robmikh/SimpleRecorder#40]
Hi, I'm trying to build this project from source in VS 2017 on Windows 10 Build 19042.928.

However when I build the solution, the compile complaints about 2 missing definitions:
1. Missing definition of CreateFreeThreaded in Direct3D11CaptureFramePool
2. Missing definition of CreateFromDirect3D11Surface in MediaStreamSample

Does someone have an idea why these definitions might be missing? Is a certain directX version required?

Best
Maurice

**Comment by robmikh** [comment]
You likely don't have the correct version of the SDK installed. You'll need version 10.0.18362.0, which you can find [here](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/). You'll want to make sure the project is set to target that SDK too. It should be set that way by default, but VS may have changed it to something else when you opened it and didn't have the right version.

Additionally, I'd recommend using at least VS 2019 to build this project.
