### ISSUE TITLE
"Use source size" causes "cannot find an encoder MFT that accepts the ... output type" exception

### ISSUE THREAD

**Issue by andrew-mi** [robmikh/SimpleRecorder#42]
"Use source size" option causes "cannot find an encoder MFT that accepts the user preferred output type" exception.
Clicking "start recording" after selecting the "use source size" resolution option causes the recording to fail.

Title: Recording failed
Description: Uh-oh! Something went wrong! 0xC00DA412 - Cannot find an encoder MFT that accepts the user preferred output type. (Exception from HRESULT: 0xC00DA412)
![image](https://user-images.githubusercontent.com/20514615/142224102-552b21d1-bd3b-4ac3-9b53-05eab175f344.png)

Monitor resolution: 3840x2160 (just a single monitor)
OS: Windows 11 22000.318
Using latest version available in Microsoft Store (as of writing).

Let me know if you need any additional information.

**Comment by robmikh** [comment]
Could you share a dxdiag from the machine? What other encoder settings did you use? I would try a lower bitrate or frame rate (or both).

You can save a dxdiag by opening the Run dialog (Win+R) and entering "dxdiag". It might ask you about signed drivers, you can say yes. After that, click the "Save All Information" button. The resulting txt file will have technical information about your machine.

**Comment by andrew-mi** [comment]
Lowering the frame rate fixes the issue.
Thanks
[DxDiag.txt](https://github.com/robmikh/SimpleRecorder/files/7560125/DxDiag.txt)

**Comment by robmikh** [comment]
Thanks for the DxDaig! This will help in the long term investigation. Closing this issue for now.

**Comment by onerob2000** [comment]
Has a new issue been opened for this? It's happening to me on export..  I have plenty of memory and disk space...
![image](https://github.com/robmikh/SimpleRecorder/assets/6371570/c26315c9-8010-47dc-9be9-02dccbe9cfc7)

**Comment by robmikh** [comment]
That looks like a different piece of software. You may want to contact the developers to get help with it.

But generally, the error means that the encoding hardware does not support the collection of settings you've selected.

**Comment by onerob2000** [comment]
> That looks like a different piece of software. You may want to contact the developers to get help with it.
> 
> But generally, the error means that the encoding hardware does not support the collection of settings you've selected.

Thank you.. So after seeing this post it made sense to attempt again with Hardware Acceleration turned off and voila, it worked.
