### ISSUE TITLE
How to capture all screens automatically?

### ISSUE THREAD

**Issue by VAllens** [robmikh/SimpleRecorder#44]
How to capture all screens automatically? 
There seems to be no api under the `Windows.Graphics.Capture` namespace.
`GraphicsCapturePicker` class, which requires the user to manually select them one by one, we want to simplify this step.

I see that there seems to be a relevant api here: https://github.com/robmikh/Win32CaptureSample/blob/master/Win32CaptureSample/util/capture.desktop.interop.h

**Comment by roman380** [comment]
From programmer perspective you can't capture 2+ screens at once (consider those have different resolutions, to start with). If you're interested in programmatic solution you just need to capture in parallel, as independent activity.

**Comment by VAllens** [comment]
Thanks @roman380 . :) 
I already have a solution, refer here: https://github.com/robmikh/WPFCaptureSample

**Comment by VAllens** [comment]
Thanks @roman380 . :)
I already have a solution, refer here: https://github.com/robmikh/WPFCaptureSample
