### ISSUE TITLE
Audio recording

### ISSUE THREAD

**Issue by Armin2208** [robmikh/SimpleRecorder#45]
The last missing thing to make this software perfect. Recording the system audio of Windows and maybe a microphone.

**Comment by robmikh** [comment]
This has come up a few times 🙂 #34 #33 #32 #21

I won't be adding audio recording to _this_ project, as I want to keep the sample focused on recording the screen. 

But I have another more complex application that records the screen as well as the audio from the given window owner (or system audio). The engine is complete and is able to record audio/video, but I'm still working out the UI. I'll let you know here once it's complete and it ships 🙂.

**Comment by Armin2208** [comment]
Nice! Will it be completely free?

**Comment by robmikh** [comment]
I haven't decided yet, I'm leaning towards trying out a commercial release on the store with a free version with fewer advanced features.  At a minimum the engine/core will be MIT licensed and on GitHub.
