### ISSUE TITLE
Recording sound

### ISSUE THREAD

**Issue by lukaszjablonski** [robmikh/SimpleRecorder#47]
This is more a feature request than an issue but it would be really great to have an option to record sound too..

P.S. I know it pops up few times already but was curious about the status.

**Comment by robmikh** [comment]
For my tracking: #45 #34 #33 #32 #21

Out of scope for this sample. There's a more comprehensive project that has audio recording but I'm currently working on something else. I'm not sure when I'll come back to the new recorder.
