### ISSUE TITLE
can't record the sound on windows 10

### ISSUE THREAD

**Issue by BRUZON444** [robmikh/SimpleRecorder#50]
the issue is simple when i record anything on the desktop or on apps when i finish the record and i save the video i can't hear any sound is this an issue on the app itself or only on my device ? please reply fast.

**Comment by robmikh** [comment]
Please use the search function, this has come up multiple times.

Also, it's a bit rude to ask someone to reply quickly like that.

**Comment by BRUZON444** [comment]
thank you sir i saw that but i still don't know how to enable the Windows.Media.Transcoding or atleast add a Windows Audio Session if you could just show me how i would be so gratfull. and also i like your programe its lightweigh than other programs and  its the thing i was looking for for that's why im trying to make it work sir.

**Comment by singhwong** [comment]
@BRUZON444 This open source project [Fluent-Screen-Recorder](https://github.com/MarcAnt01/Fluent-Screen-Recorder) may help you. It is based on SimpleRecorder and adds the feature to record audio.
